### ISSUE TITLE
[FEATURE]  Add a Rate function to Register UE in specified Rate 

### ISSUE THREAD

**Issue by sambitcom** [HewlettPackard/PacketRusher#120]
**Is your feature request related to a problem? Please describe.**
I am trying to run  ./packetrusher  multi-ue -n 20000 -l.  But the Signaling TP and pps  is very low. I want to add a function to support rate of registration so that it runs on that speed. For example 100 Reg/sec .  

**Describe the solution you'd like**
A clear and concise description of what you want to happen. If applicable, inform the specifications and sections the defines the behavior.

**Describe alternatives you've considered**

**Additional context**

**Comment by linouxis9** [comment]
Hi @sambitcom,

Have you tried something like `./packetrusher multi-ue -n 20000 --timeBetweenRegistration 50 --loop`.
Otherwise, we are also working on #31 which would add that kind of parameters!

Thanks and cheers,
Valentin

**Comment by sambitcom** [comment]
Hi Valentin,

I have tried such option but I am getting below error 
NFO[0051] [GNB] Initiating PDU Session Resource Setup Response 
FATA[0051] [GNB][AMF] Error sending Initial Context Setup Response: Error sending NGAP message %!(EXTRA syscall.Errno=no buffer space available) 

Is there anylogs you required to debug or any workaround available to continue my test?

Regards,
SambitM

**Comment by linouxis9** [comment]
Hi,

It seems that are you sending more messages than your AMF can handle from your gNodeB at once. Starts with --timeBetweenRegistration 500 and reduce the number until just before you get this issue.

Thanks,
Valentin

**Comment by sambitcom** [comment]
I have successfully tested with higher Control plane TP above use case by tuning sctp perimeter in linux.  You may close this ticket.

**Comment by linouxis9** [comment]
Hi @sambitcom,

Would you mind sharing the SCTP parameters you tweaked?

Thanks a lot for confirming it worked for you!

Valentin
