### ISSUE TITLE
[BUG]  [UE][DATA] Unable to create VRF for UEoperation not supported 

### ISSUE THREAD

**Issue by Noufel17** [HewlettPackard/PacketRusher#139]
**Describe the bug**
[UE][DATA] Unable to create VRF for UEoperation not supported 

**To Reproduce**
simple one ue test
the UE connects via the AMF and gets assigned a PDU session but then doesn't create the VRF, I'm already using UERANSIM and it works normally. I am running the whole network on Kubernetes, can docker support be the issue? but again I run UERANSIM totally fine

**Expected behavior**
normal VRF creation

**Screenshots**
![image](https://github.com/user-attachments/assets/aa2b681d-59dd-4887-9385-a4bc3969c0d9)

**Architecture (please complete the following information):**
- OS: [e.g. Ubuntu on GCP]
- Platform [e.g. x86_64, ...]
- Kernel [e.g. 5.0.0.23-generic]
- I'm using this repo's dockerization to create the image used in kubernetes pod

**Log:**
root@packetrusher-65bfdd85-jwqg5:/PacketRusher# ./packetrusher ue
INFO[0000] Selecting 10.100.192.2 for host 10.100.192.2 as AMF's IP address 
INFO[0000] Selecting 10.100.144.42 for host 10.100.144.42 as gNodeB's N3/Data IP address 
INFO[0000] Selecting 10.100.64.42 for host 10.100.64.42 as gNodeB's N2/Control IP address 
INFO[0000] Loaded config at: /PacketRusher/config/config.yml 
INFO[0000] PacketRusher version 1.0.1                   
INFO[0000] ---------------------------------------      
INFO[0000] [TESTER] Starting test function: Testing an ue attached with configuration 
INFO[0000] [TESTER][UE] Number of UEs: 1                
INFO[0000] [TESTER][UE] disableTunnel is false          
INFO[0000] [TESTER][GNB] Control interface IP/Port: 10.100.64.42/38412~ 
INFO[0000] [TESTER][GNB] Data interface IP/Port: 10.100.144.42/2152 
INFO[0000] [TESTER][AMF] AMF IP/Port: 10.100.192.2/38412 
INFO[0000] ---------------------------------------      
INFO[0000] [GNB] SCTP/NGAP service is running           
INFO[0000] [GNB] Initiating NG Setup Request            
INFO[0000] [GNB][SCTP] Receive message in 0 stream      
INFO[0000] [GNB][NGAP] Receive NG Setup Response        
INFO[0000] [GNB][AMF] AMF Name: AMF                     
INFO[0000] [GNB][AMF] State of AMF: Active              
INFO[0000] [GNB][AMF] Capacity of AMF: 255              
INFO[0000] [GNB][AMF] PLMNs Identities Supported by AMF -- mcc: 208 mnc:93 
INFO[0000] [GNB][AMF] List of AMF slices Supported by AMF -- sst:01 sd:010203 
INFO[0000] [GNB][AMF] List of AMF slices Supported by AMF -- sst:01 sd:112233 
INFO[0001] [TESTER] TESTING REGISTRATION USING IMSI 0000000001 UE 
INFO[0001] [GNB] Received incoming connection from new UE 
INFO[0001] [UE] Initiating Registration                 
INFO[0001] [UE] Switched from state 0 to state 1        
INFO[0003] [GNB][SCTP] Receive message in 0 stream      
INFO[0003] [GNB][NGAP] Receive Downlink NAS Transport   
INFO[0003] [UE][NAS] Message without security header    
INFO[0003] [UE][NAS] Receive Authentication Request     
INFO[0003] [UE][NAS][MAC] Authenticity of the authentication request message: OK 
INFO[0003] [UE][NAS][SQN] SQN of the authentication request message: VALID 
INFO[0003] [UE][NAS] Send authentication response       
INFO[0003] [UE] Switched from state 1 to state 2        
INFO[0003] [GNB][SCTP] Receive message in 0 stream      
INFO[0003] [GNB][NGAP] Receive Downlink NAS Transport   
INFO[0003] [UE][NAS] Message with security header       
INFO[0003] [UE][NAS] Message with integrity and with NEW 5G NAS SECURITY CONTEXT 
INFO[0003] [UE][NAS] successful NAS MAC verification    
INFO[0003] [UE][NAS] Receive Security Mode Command      
INFO[0003] [UE][NAS] Type of ciphering algorithm is 5G-EA0 
INFO[0003] [UE][NAS] Type of integrity protection algorithm is 128-5G-IA2 
INFO[0003] [GNB][SCTP] Receive message in 0 stream      
INFO[0003] [GNB][NGAP] Receive Initial Context Setup Request 
INFO[0003] [GNB][UE] UE Context was created with successful 
INFO[0003] [GNB][UE] UE RAN ID 1                        
INFO[0003] [GNB][UE] UE AMF ID 17                       
INFO[0003] [GNB][UE] UE Mobility Restrict --Plmn-- Mcc: 208 Mnc: 93 
INFO[0003] [GNB][UE] UE Masked Imeisv: 1110000000ffff00 
INFO[0003] [GNB][UE] Allowed Nssai-- Sst: [01 01] Sd: [010203 112233] 
INFO[0003] [GNB][NGAP][AMF] Send Initial Context Setup Response. 
INFO[0003] [GNB] Initiating Initial Context Setup Response 
INFO[0003] [GNB][NGAP] No PDU Session to set up in InitialContextSetupResponse. 
INFO[0003] [UE][NAS] Message with security header       
INFO[0003] [UE][NAS] Message with integrity and ciphered 
INFO[0003] [UE][NAS] successful NAS CIPHERING           
INFO[0003] [UE][NAS] successful NAS MAC verification    
INFO[0003] [UE][NAS] Receive Registration Accept        
INFO[0003] [UE][NAS] UE 5G GUTI: &{119 11 [242 2 248 57 202 254 0 0 0 0 5]} 
INFO[0003] [UE] Switched from state 2 to state 3        
INFO[0003] [UE] Initiating New PDU Session              
INFO[0003] [GNB][SCTP] Receive message in 0 stream      
INFO[0003] [GNB][NGAP] Receive Downlink NAS Transport   
INFO[0003] [UE][NAS] Message with security header       
INFO[0003] [UE][NAS] Message with integrity and ciphered 
INFO[0003] [UE][NAS] successful NAS CIPHERING           
INFO[0003] [UE][NAS] successful NAS MAC verification    
INFO[0003] [UE][NAS] Receive Configuration Update Command 
INFO[0003] [UE] Initiating Configuration Update Complete 
INFO[0004] [GNB][SCTP] Receive message in 0 stream      
INFO[0004] [GNB][NGAP] Receive PDU Session Resource Setup Request 
INFO[0004] [GNB][NGAP][UE] PDU Session was created with successful. 
INFO[0004] [GNB][NGAP][UE] PDU Session Id: 1            
INFO[0004] [GNB][NGAP][UE] NSSAI Selected --- sst: NSSAI was not selected sd: NSSAI was not selected 
INFO[0004] [GNB][NGAP][UE] PDU Session Type: ipv4       
INFO[0004] [GNB][NGAP][UE] QOS Flow Identifier: 1       
INFO[0004] [GNB][NGAP][UE] Uplink Teid: 36              
INFO[0004] [GNB][NGAP][UE] Downlink Teid: 1             
INFO[0004] [GNB][NGAP][UE] Non-Dynamic-5QI: 9           
INFO[0004] [GNB][NGAP][UE] Priority Level ARP: 8        
INFO[0004] [GNB][NGAP][UE] UPF Address: 10.100.128.18 :2152 
INFO[0004] [GNB] Initiating PDU Session Resource Setup Response 
INFO[0004] [UE][NAS] Message with security header       
INFO[0004] [UE][NAS] Message with integrity and ciphered 
INFO[0004] [UE][NAS] successful NAS CIPHERING           
INFO[0004] [UE][NAS] successful NAS MAC verification    
INFO[0004] [UE][NAS] Receive DL NAS Transport           
INFO[0004] [UE][NAS] Receiving PDU Session Establishment Accept 
INFO[0004] [UE][NAS] PDU session QoS RULES: [1 0 6 49 49 1 1 255 1] 
INFO[0004] [UE][NAS] PDU session DNN: internet          
INFO[0004] [UE][NAS] PDU session NSSAI -- sst: 1 sd: 123 
INFO[0004] [UE][NAS] PDU address received: 10.5.0.12    
FATA[0005] [UE][DATA] Unable to create VRF for UEoperation not supported 

**Additional context**
Please Help I really don't have much time. will be much appreciated.

**Comment by linouxis9** [comment]
Hi @Noufel17,

You should try running `sudo modprobe vrf` and try running PacketRusher again :-)

Thanks and cheers,
Valentin

**Comment by Noufel17** [comment]
thank you @linouxis9 it worked
