### ISSUE TITLE
Multi UEs with traffic with a single PacketRusher process

### ISSUE THREAD

**Issue by linouxis9** [HewlettPackard/PacketRusher#14]

**Comment by Paola-Jimenez** [comment]
Hello,

Is it possible to generate certain amount of traffic per UE? I would like to execute a performance testing, so I am looking to configure 1000 UEs, each one of them generating traffic to de 5GCore.

Thanks in advance!

**Comment by linouxis9** [comment]
Hi @Paola-Jimenez! Thanks for being interested in PacketRusher!!
Yes it is possible! However, due to a limitation in PacketRusher, you'll need 1000 gNodeB being simulated by PacketRusher if you want to do traffic on 1000 UEs in parallel. To do that, simply you need to have a network interface (or multiple network interfaces) with 1000 continous IPs on N2/N3: https://github.com/HewlettPackard/PacketRusher/discussions/83 and 1000 UEs provisioned in your 5GC with the same key/opc and all 1000 continous MSIN/IMSI.
Then you can run 1000 iperf3 instances on your N6 network, and run a single iperf3 instance per UE VRF.

If you do not have 1000 contiguous IPs or IMSI, you can split in smaller groups:
eg. first PacketRusher instance has 192.128.1.0/24 IPs for its gNodeB and MSIN 0000000001 - 0000000250, a second PacketRusher instance with IPs to be used for gNodeB 172.16.1.0/24  and MSIN 0000000250 - 0000000500...)
