### ISSUE TITLE
[BUG] No VRF Interfaces Created When Using Multiple-UE

### ISSUE THREAD

**Issue by Mouradnetworking** [HewlettPackard/PacketRusher#144]
**Describe the bug**

When launching multiple User Equipment (UE), no Virtual Routing and Forwarding (VRF) interfaces are created for the UEs. 

**Screenshots**
[
![disabled](https://github.com/user-attachments/assets/72f68c76-2c7f-4459-a92b-334da64613eb)
](url)

**Comment by linouxis9** [comment]
Hi @Mouradnetworking,

This is expected behavior, you need to add the --tunnel option!

Thanks and cheers,
Valentin

**Comment by Mouradnetworking** [comment]
Yes yes, I found it, and I’m back to add a comment to my issue regarding the addition of -t and --dedicatedGnb.

Thank you for your response!

**Comment by Mouradnetworking** [comment]
Ex: sudo ./packetrusher multi-ue -n 5 --tunnel-vrf -t --dedicatedGnb

**Comment by Mouradnetworking** [comment]
@linouxis9 But not every VRF interface is assigned an IP address.
![image](https://github.com/user-attachments/assets/93d86ca3-497e-4f90-b673-36b1a269b74a)
