### ISSUE TITLE
[FEATURE] USRP

### ISSUE THREAD

**Issue by huahuaLover** [HewlettPackard/PacketRusher#146]
if the project support usrp?

**Comment by linouxis9** [comment]
Hi @huahuaLover,

The goal of this project is the performance and signalling procedures testing of a 5G Core without the need of any specific hardware, with the usage of simulated gNB/UE and skipping any of the radio stack.
USRP is as such out of the scope.

Thanks for your interest in PacketRusher!

Valentin

**Comment by huahuaLover** [comment]
if the project support handover between 5G and 4G by N26

**Comment by linouxis9** [comment]
This project only supports 5G protocols: eg. NGAP and NAS-5GS, support for S1AP and NAS-EPC would be needed before being able to support such handover.
Help is wanted and appreciated if you would like to contribute the support of these protocols! @huahuaLover
