### ISSUE TITLE
change the function

### ISSUE THREAD

**Issue by huahuaLover** [HewlettPackard/PacketRusher#147]
if i want to change the function of PlainNasDecode,how to change it?i observe that it is included in the free5gc libraby,so i can not find the defination of PlainNasDecode in the PacketRusher project.
![image](https://github.com/user-attachments/assets/4d5fc109-1e64-43c2-bcf5-5bd0fae5f274)

**Comment by linouxis9** [comment]
Hi @huahuaLover,

It's nice to see you using PacketRusher. The way to go would be to fork github.com/free5gc/nas, and replace github.com/free5gc/nas from the go.mod and in the PacketRusher files with your fork (eg. a big search and replace in the project doing github.com/free5gc/nas -> github.com/huahuaLover/nas).

Thanks and cheers,
Valentin

**Comment by huahuaLover** [comment]
Thank you very much for your timely reply, which has let me know how to make the modifications. I would like the UE (User Equipment) to receive additional parameters, so it's necessary to modify the decoding function.
