### ISSUE TITLE
[BUG] Unable to create tunnel for UE with multi-ue option

### ISSUE THREAD

**Issue by avrodriguezgrad** [HewlettPackard/PacketRusher#88]
**Describe the bug**
I'm trying to use the multi-ue option with only 2 UEs for testing. Only with _multi-ue -n 2_, I have the log message telling "Interface for UE X has not been created. Tunnel has been disabled" but, if I exec _multi-ue -n 2 --tunnel-vrf_, I have exactly the same message, like if it's ignoring the vrf option. 

I don't know if I'm missing something in terms of configuration. 

**To Reproduce**
Deploy PacketRusher with `./packetrusher --config config.yml multi-ue -n 1 --tunnel-vrf true`

**Expected behavior**
VRF tunnel interfaces have to be created.

**Screenshots**

**Architecture (please complete the following information):**
- OS: Ubuntu 20.04
- Platform: x86_64
- Kernel: 5.4.0-100-lowlatency

**Log:**

**Pcap:**

**Additional context**

**Comment by linouxis9** [comment]
Hi @avrodriguezgrad!

Glad to see you using PacketRusher, you may see https://github.com/HewlettPackard/PacketRusher/discussions/83 for more reference on how to use multi-ue. Basically, it seems you are missing the `--tunnel` option.

Cheers,
Valentin

**Comment by avrodriguezgrad** [comment]
Oh, I did not see in discussions to search about the bug, thank you!

Currently, is it impossible to use only 1 gNB for multiple UEs? Do you have in your roadmap this feature?

**Comment by avrodriguezgrad** [comment]
I see. This creates me another doubt. Without the tunnel option, I'm having the above message about interface's not being created. Can I create the interface manually? Or what do you recommend me to generate traffic from UEs?

**Comment by linouxis9** [comment]
Without the tunnel option, the interface is indeed not being created. As such, you cannot do user plane traffic. You are limited to doing control plane procedures (Xn/NGAP handover, Idling, Deregistration, Creation/Deletion of PDU Sessions...)
You could however indeed generate traffic manually from the UEs without the tunnels after PacketRusher has etablished the PDU Sessions, by using a tool like Cisco TRex which can generate raw GTP-U traffic. This is something I would like to investigate as well, but don't have the time to work on for now.

**Comment by avrodriguezgrad** [comment]
Okey, thanks for the explanation! If I have time the following weeks, I'll try to investigate this too.

Thanks again! 
Álvaro
